Dockerfile

would like to add the EGIAuthenticator from that branch to test it before merging it

Use new EGI Authenticator

---

Dockerfile
egi_notebooks_hub/d4science.py

Move the external code here, no need to keep it in a separate repo.

D4scienceauth

---

.github/CODEOWNERS
.github/CODE_OF_CONDUCT.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
COPYRIGHT

Create the contribute guides and templates for issues/PRs
----
**Related issue :** #12

Add contributing info and templates

---

egi_notebooks_hub/egiauthenticator.py
egi_notebooks_hub/egispawner.py

Add the id_token and move the default location to /var/run/secrets/egi.eu
Also make it configurable just in case we change our mind about the best
place to store those tokens
----

Include id_token and fix location of tokens

---

.travis.yml
egi_notebooks_hub/d4science.py
egi_notebooks_hub/egiauthenticator.py
egi_notebooks_hub/egispawner.py
test-requirements.txt
tox.ini

- Add some testing, start with linting
- Fix flake8 issues
----

Add some testing

---

egi_notebooks_hub/egiauthenticator.py
egi_notebooks_hub/egispawner.py

Fix the name of the function and set to None the id token to remove it if present from before
----

Fix the refresh with id tokens

---

egi_notebooks_hub/egispawner.py

Ensures that the secret for the tokens always exists to avoid
issues with pods created without being authenticated the usual
way (e.g. monitoring)
----

Ensure that secret exists

---

.github/workflows/docker.yml
Dockerfile

Fix the build of containers

---

egi_notebooks_hub/d4science.py

Add vre to the spawner environemnt for d4science

---

.github/workflows/docker.yml

Add latest as tag

---

.github/workflows/docker.yml

Move to new format

---

.github/workflows/docker.yml

Avoid pushing things when not in master branch
---

Only on master branch

---

templates/401.html
templates/login.html

Update the login page to show CESNET as current operator
---

Use CESNET logo

---

egi_notebooks_hub/d4science.py
egi_notebooks_hub/egiauthenticator.py
egi_notebooks_hub/egispawner.py

Move to new tokens API and add support for local mappings in the storage
---

Improve datahub support

---

templates/login.html

Update limits 
---
No issue opened

Updated limits for default resources allocated per user

---

Dockerfile
templates/401.html
templates/login.html

Add VO info

---

egi_notebooks_hub/onedata.py

Does not try to configure all the onedata stuff if there is information missing. Fixes monitoring 
---

Avoid setting up onedata if not available

---

egi_notebooks_hub/onedata.py

Check if the authentication was valid from the parent class before
attempting to get any of information from the user
It fixes issues found for some users in the production instance
---

Do not assume valid authentication

---

templates/login.html

Add links to policy

---

egi_notebooks_hub/d4science.py

Use new conf for jupyter resource usage extension

---

egi_notebooks_hub/d4science.py

from https://support.d4science.org/issues/22758#change-131559
from https://support.d4science.org/issues/22758#change-131559
---

Update  iopub_data_rate_limit 

---

egi_notebooks_hub/onedata.py

Add an option for oneclient extra arguments
---

Add an option for extra arguments for oneclient

---

egi_notebooks_hub/welcome.py
templates/logout.html
templates/welcome.html

Avoid the login page whenever a user gets to / or similar and redirect directly to Check-in if possible
---

New welcome page

---

Dockerfile
egi_notebooks_hub/d4science.py
requirements.txt

Create profile list according to the information system in D4Science
---

D4Science profile builder

---

egi_notebooks_hub/egiauthenticator.py

use the new endpoints as listed in https://docs.egi.eu/providers/check-in/sp/#endpoints
---

Update Check-in endpoints

---

templates/login.html
templates/welcome.html

Update link from decommissioning EGI Marketplace to EOSC portal.

Update marketplace link

---

egi_notebooks_hub/onedata.py

Suggested by Lukasz Opiola
---

add -z option to fusermount

---

templates/login.html
templates/welcome.html

Resources are changing frequently and it is difficult to keep the track in the static welcome page.

Better to remove info about resources from welcome page

---

Dockerfile
egi_notebooks_hub/d4science.py
egi_notebooks_hub/egiauthenticator.py
egi_notebooks_hub/egispawner.py
egi_notebooks_hub/onedata.py
requirements.txt

Make sure that the hub works with the latest version of z2j 
- Update base image
- Require newer kubespawner
- Fix async calls 
---

Jump to 2.0.0

---

egi_notebooks_hub/d4science.py

Adapt to new environment variables for D4science
- Remove D4science gcube token based authentication
- use the new variable names
---
**Related issue :** https://support.d4science.org/issues/24572

d4science context

---

CHANGELOG.md
egi_notebooks_hub/egiauthenticator.py
templates/egi-login.html

Calls the spawner to ensure that the secret is updated
---
**Related issue :** #102

Get back the call to propagate the secret

---

egi_notebooks_hub/d4science.py

Volumes are read-write for those users with the Data-Manager role for
the context being evaluated. The name Data-Manager role can be configured.
Related: https://support.d4science.org/issues/25256
---
**Related issue :** https://support.d4science.org/issues/25256

feat: Support data manager role for volumes

---

Dockerfile
egi_notebooks_hub/d4science.py
requirements.txt

Bring several fixes to make the hub work on GCP:
- Make the use of the sidecar for mounting the workspace, let it be handled by the single-user image instead.
- Upgrade the image to the latest z2j hub images (v3.2.1)
- Fix the authenticator code to fetch the D4Science context at the right place
- Bring the ophidia support into the spawner
---

D4Science fixes

---

egi_notebooks_hub/egiauthenticator.py

Avoid having random groups reported as primary
---

Do not let us guess the primary group

---

ec-templates/403.html

Avoid using "error" and "ecl-container" together

---

egi_notebooks_hub/egiauthenticator.py

Adapt the regex to the namespaces used in the EOSC EU Node:
- Testing: `urn:geant:eosc-federation.eu`
- Staging: `urn:geant:eosc-federation.eu`
- Production: `urn:geant:open-science-cloud.ec.europa.eu`
Personal projects are in the form:
`<urn-namespace>:group:pp-0190356a-ac97-db53-21c0-df7cd31a47c4`
---

Improve regex for personal projects

---

Dockerfile
requirements.txt

https://z2jh.jupyter.org/en/latest/changelog.html#id5
---

Update hub to 3.3.8

---

Dockerfile
egi_notebooks_hub/egiauthenticator.py
requirements.txt

- Upgrade base image*
- Upgrade to match versions in the base image
- Adapt authentication to newer OAuthenticator code
---

Update to Zero2JupyterHub 4.0

---

ec-templates/accept-share.html
ec-templates/error.html
ec-templates/oauth.html
ec-templates/token.html

* Updating current templates with newest Jupyterhub 5 template updates from https://github.com/jupyterhub/jupyterhub/tree/a8500a31a9bc77a9829e903693462a7da38fee52/share/jupyterhub/templates
* Fixing broken template
* Fixing template content alignment
---

Updating EC templates

---

.github/dependabot.yml

Check python packages

---

Dockerfile

This PR upgrages base k8s Hub image which contains Jupyterhub 5.3.0
---

Upgrading to Hub k8s 4.2.0 image containing 5.3.0 Jupyterhub

---

egi_notebooks_hub/egiauthenticator.py

Better detect issues with refresh exchange

---

templates/401.html

Update GGUS URL

---

ec-templates/not_running.html

This PR reorders error message blocks on not-running spawn template for better readability.
---

Fixing spawn error message blocks for better readability
