.github/workflows/lint.yml, egi_notebooks_hub/d4science.py
We enable WPS discovery only if requested, as a query to IC could be slow and it could slow down the loading of JupyterHub from the VRE
---
=> Enable wps discovery only if configured

egi_notebooks_hub/egiauthenticator.py, requirements.txt
use the new oauthenticator version, which now implements the allowed_groups feature.
By using the new configuration like 
`
claim_groups_key: "eduperson_entitlement"
`
`
allowed_groups:
`
`
- urn:egi.eu:group:fedcloud-users
`
`
- urn:mace:egi.eu:www.egi.eu:techsolutions:member@egi.eu
`
we can now remove the implementation of the allowed entitlements inside the EGICheckinAuthenticator which seems to be broken now. ( hence i removed also the allowed affiliation check)
---
=> update to new oauthenticator version, use allowed_groups feature

templates/401.html
Direct link to [Notebooks#Service Modes](https://docs.egi.eu/users/notebooks/#service-modes) in 401 error page to be more easy for users to get information about granting access, when rejected.
Also minor spellcheck fixes.
I'm not sure about the "Unauthorised" word. It is not in the en_US dictionary (using hunspell), so I modified it too. But maybe it is typically used and would be OK?
---
**Related issue :** https://jira.egi.eu/browse/IMSCHM-58
=> Link EGI documentation related to notebooks in 401 page

egi_notebooks_hub/onedata.py
So the datahub does not fail when starting
Avoid failing whenever datahub is not available. 
---
**Related issue :** #75
=> Add a new onedata_failsafe option

egi_notebooks_hub/egiauthenticator.py, egi_notebooks_hub/egispawner.py, egi_notebooks_hub/onedata.py
Filter profiles and annotate a primary group. The code is separated between authentication (picking groups) and the spawner (performing profile filtering and annotating the primary group).
Filter out profiles depending on the VO membership of the user.
Those profiles where `vo_claims` is defined (List of strings), they will only be shown as options if the user has any of those exact claims in their entitlements.
Example:
```
profileList:
- display_name: 'Only for access VO'
vo_claims:
- urn:mace:egi.eu:group:vo.access.egi.eu:role=member#aai.egi.eu
kubespawner_override:
image: 'eginotebooks/single-user-d4science:sha-8ce52e1'
cpu_limit: 1
mem_limit: 1G
```
The primary group is selected from the user claims - the first occurrence in the `Authenticator.allowed_groups` - and annotatation …
=> Filter profiles + annotation of the primary group for accounting

egi_notebooks_hub/d4science.py, egi_notebooks_hub/services/d4science_spawn.py
Profiles can be filtered not just by the permission but also via the
"Name" of the "ServerOption" as delivered by D4Science. This
implementation users JupyterHub's named servers to apply the filtering.
A helper service facilitates redirecting to the right spawner page.
---
**Related issue :** https://support.d4science.org/issues/24827
=> feat: Filter profiles depending on the server name

egi_notebooks_hub/egiauthenticator.py
Users created manually won't have access tokens or refresh tokens and therefore will fail to refresh. Detect this situation so we can have some stress tests in place.
Probably should check the validity of the access token instead of this `refresh_info` that is created after successful call of this function. 
---
=> Do not try to refresh non Check-in users

egi_notebooks_hub/d4science.py, egi_notebooks_hub/egiauthenticator.py, egi_notebooks_hub/services/d4science_spawn.py
Several fixes to the spawner and authenticator to better work on GKE with D4Science.
Namely:
- Avoid error 500 when context is not available
- Add namespaces as option to spawner
- Add image override option to spawner
- Remove tornado setting from the spawner
- Add label as authentication option
---
=> GKE improvements for D4science

.github/workflows/lint.yml, egi_notebooks_hub/d4science.py, egi_notebooks_hub/egiauthenticator.py, egi_notebooks_hub/services/api_wrapper.py, requirements.txt
Make the API wrapper configurable so it runs beyond the simple local scenario
---
=> jwt settings

.github/workflows/lint.yml, egi_notebooks_hub/d4science.py, egi_notebooks_hub/egiauthenticator.py, setup.cfg
Implement the support for the personal projects as the primary group of the user so this can be properly reported in accounting.
Creates a new `EOSCNodeAuthenticator` that will try to get the primary group of the user from the entitlements by matching a `personal_project_re` regular expression with default value:
```
r"^urn:geant:eosc-federation.eu:group:pp:Personal%20Project%20Name-(.*)$"
```
If the RE contains a group, the match will be used as the name for the primary group of the user. If it does not match, the primary group will be the first group of the user that matches the `allowed_groups`.
Sample configuration
```
c.JupyterHub.authenticator_class = "eoscauthenticator"
c.EOSCNodeAuthenticator.allow_all = True
c.EOSCNodeAuthenticator.claim_groups_key = "eduperson_entitlement" …
```
=> EOSC Node AAI

egi_notebooks_hub/egiauthenticator.py, egi_notebooks_hub/services/api_wrapper.py
Performs a token exchange request to get a refresh token whenever this is not yet available for the user.
---
=> Token exchange to get refresh token

egi_notebooks_hub/__init__.py, egi_notebooks_hub/egiauthenticator.py, requirements.txt
Make it easier to discover versions in runtime
---
=> Add version to the package

egi_notebooks_hub/egiauthenticator.py, egi_notebooks_hub/egispawner.py, requirements.txt
- **Need newer oauthenticator**
- **Make use of the groups**
- **Better filter**
---
=> Fix profile filter

egi_notebooks_hub/egiauthenticator.py, requirements.txt
Remove the stale user info whenever the refresh process fails so the user is forced to authenticate again from scratch. This will force obtaining a new refresh token, before the broken token would remain unchanged when loggin in via JWT.
Also check the validity of the access token so the refresh does not need to happen if the user has a valid token in place.
---
=> Enforce refresh token clean-up

ec-templates/403.html, ec-templates/admin.html, ec-templates/egi-login.html, ec-templates/error.html, ec-templates/home.html, ec-templates/logout.html, ec-templates/not_running.html, ec-templates/oauth.html, ec-templates/page.html, ec-templates/spawn.html, ec-templates/spawn_pending.html, ec-templates/stop_pending.html, ec-templates/token.html, requirements.txt
Move all templates here, so we override the hub styles completely
---
=> Add templates

egi_notebooks_hub/egiauthenticator.py
Assume the user can somehow be authorized afterwards. Potentially we could look for an alternative attribute instead of `sub` as fallback.
---
=> Create usernames on the fly for service accounts

CHANGELOG.md, README.md
Get ready for a 0.2.0 release
---
=> Getting ready for 0.2.0

egi_notebooks_hub/egiauthenticator.py
Use the introspection endpoint instead of the userinfo when coming through jwt authentication route. This allows for getting information for service accounts that are delivering an empty userinfo.
---
=> Use introspection

egi_notebooks_hub/services/api_wrapper.py
This allows for certain slow operations like a DELETE to complete
without us throwing an error.
---
=> Add timeout to the calls to the hub api

egi_notebooks_hub/egiauthenticator.py
Brings a fallback claim for those _users_ that do not have a user name, so considered as _service accounts_. The name of the claim is configured with `servicename_claim`. 
It also tries to avoid the refresh for those users that cannot be refreshed. This assumes the users that need to be refreshed actually have a valid refresh token
---
=> Add service accounts

egi_notebooks_hub/egispawner.py
Add a new option for the spawner `mount_secrets_volume` that will determine whether the secrets volume is mounted or not in the user environment (but still potentially available in the sidecars). As being part of the spawner configuration, it can be used in the `kubespawner_overrides`:
```
singleuser:
profileList:
- display_name: Default environment
description: >
The default notebook environment includes Python, R, Julia and Octave kernels.
default: true
kubespawner_override:
args:
- "--CondaKernelSpecManager.env_filter='/opt/conda$'"
- display_name: No secrets environment
description: >
Look ma! no screts.
kubespawner_override:
args:
- "--CondaKernelSpecManager.env_filter='/opt/conda$'"
mount_secrets_volume: false
```
---
=> Move the mount_secrets_volume option to the configuration
